[project]
name = "langchain-moss"
version = "0.1.0"
description = "An integration package for LangChain and Moss"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "inferedge-moss>=1.0.0b8",
    "langchain-core>=1.2.6",
    "pydantic>=2.12.5",
]
